#!/bin/bash
echo "/etc/hosts" > "/etc/hosts.original"
echo "/etc/hosts.hostsblock" >> "/etc/hosts"
chown root:wheel "/etc/hosts"
chmod 644 "/etc/hosts"
killall -9 discoveryd
killall -9 mDNSResponder
exit 0
